Feature/mob mod
whiteoctopuscodes/ice-cream_landing pull request #14
Opened 2022-06-25 20:07 UTC by Hubarenko10

2022-06-25 20:19 UTC, NataliiaPasaman commented
> _ No description provided. _

1.В html в svg немає width/height
2. клас menu__position задаєш абсолютне позиціонування - додай top: 0; left: 0;
3. line-height - не вскрізь стоїть множник
4. в лінках є margin-top i margin-bottom - навіщо це?

2022-06-25 21:18 UTC, Hubarenko10 commented
+

2022-06-25 21:18 UTC, Hubarenko10 commented
done)

2022-06-26 09:37 UTC, whiteoctopuscodes requested changes

2022-06-26 09:37 UTC, whiteoctopuscodes commented on src/partials/mobile-modal.html
> +           <svg class="menu__icon" width="13.5px" height="14px" >
нужно, чтобы размеры были цельные

2022-06-26 09:37 UTC, whiteoctopuscodes commented on src/partials/mobile-modal.html
> +<div class="backdrop hide is_hidde " data-menu>
ис-хиден с ошибкой

2022-06-26 09:37 UTC, whiteoctopuscodes commented on src/sass/components/_mobile-modal.scss
> +  font-style: normal;
такие пункты как стайл нормал, стоят в базовых настройкай

2022-06-26 09:37 UTC, whiteoctopuscodes commented on src/sass/components/_mobile-modal.scss
> +.backdrop {
ты меню через бекдроп сделал? а это лишние конструкции, опробуй через меню позишн фиксед

2022-06-26 19:33 UTC, merged