Feature contact
whiteoctopuscodes/ice-cream_landing pull request #17
Opened 2022-06-26 10:09 UTC by MarynaYa

в секции ховер/ фокус на майл, тел, кнопки.

2022-06-26 11:37 UTC, whiteoctopuscodes requested changes

2022-06-26 11:37 UTC, whiteoctopuscodes commented on src/partials/contact.html
> +    <section class="contact">
доп класс на секцию петеряла, который секция

2022-06-26 11:37 UTC, whiteoctopuscodes commented on src/sass/_contact-mob.scss
> +        padding-right: 20px;
настройки класса контакт есть в проекте,
лишняя скобка в селекторе цвета

2022-06-26 11:37 UTC, whiteoctopuscodes commented on src/sass/_contact-mob.scss
> +        &__container {
по плану карточки не должны тянуться?

2022-06-26 11:37 UTC, whiteoctopuscodes commented on src/sass/_contact-mob.scss
> +        max-width: 280px;
такие карточки тянуться не будут, не будет респонсивности

2022-06-26 11:37 UTC, whiteoctopuscodes commented on src/partials/contact.html
> +                    <button class="contact__agency-name" type="button">CAFE</button>
это не совсем кнопки, это п с оформлением)

2022-06-26 11:37 UTC, whiteoctopuscodes commented on src/sass/_contact-mob.scss
> +        width: 100%;
попробуй задать на лист падинги, чтобы не задавать фиксированные размеры компонентам. Они тогда сами подстроятся, это лучше для дальнейшего адаптива

2022-06-26 11:37 UTC, whiteoctopuscodes commented on src/sass/_contact-mob.scss
> +        width: 100%;
+ у списков обнуление и так есть

2022-06-26 11:37 UTC, whiteoctopuscodes commented on src/partials/contact.html
> +                                <a class="tell-info" href="tell:+610383766284 ">+61(0) 383 766 284 </a>
tel с одной л

2022-06-26 11:37 UTC, whiteoctopuscodes commented on src/partials/contact.html
> +        <div class="contact__container">
у тебя полностью снесен контейнер, значит его размеры для тебя не призовутся

2022-06-26 11:48 UTC, MarynaYa commented on src/sass/_contact-mob.scss
> +        padding-right: 20px;
background-image: linear-gradient(
        to bottom, 
       #ffffff 362px, 
        $secondaryBackground 362px);

2022-06-26 11:55 UTC, MarynaYa commented on src/partials/contact.html
> +                    <button class="contact__agency-name" type="button">CAFE</button>
я увидела такой вариант у Ярослава и применила. Он объяснил что так быстрее можно центровать текст и формить. Если это принципиально - изменю

2022-06-26 11:56 UTC, MarynaYa commented on src/sass/_contact-mob.scss
> +        &__container {
на    &__container {  width: 100%;  - изменила

2022-06-26 11:57 UTC, MarynaYa commented on src/partials/contact.html
> +    <section class="contact">
<section class="contact section">   - изменила

2022-06-26 12:08 UTC, MarynaYa commented on src/partials/contact.html
> +                                <a class="tell-info" href="tell:+610383766284 ">+61(0) 383 766 284 </a>
изменила

2022-06-26 12:09 UTC, MarynaYa commented on src/sass/_contact-mob.scss
> +        width: 100%;
обнуления маржин и паддинг - убрала

2022-06-26 12:16 UTC, MarynaYa commented on src/partials/contact.html
> +        <div class="contact__container">
contact__container container - исправила

2022-06-26 12:25 UTC, MarynaYa commented on src/sass/_contact-mob.scss
> +        width: 100%;
Не совсем понимаю (не знаю), какие падинги можно задать на UL, если падинг есть у секции, контейнера и Li.

2022-06-26 12:26 UTC, MarynaYa commented on src/sass/_contact-mob.scss
> +        max-width: 280px;
это наверное = комменту про падинг на UL

2022-06-27 14:26 UTC, whiteoctopuscodes approved these changes

2022-06-27 14:26 UTC, whiteoctopuscodes commented on src/sass/_contact-mob.scss
> +    .list {
обнуления лист и абзацов есть

2022-06-27 16:36 UTC, merged